apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'az-classifier'
        kubernetes_sd_configs: 
          - role: endpoints 
            namespaces: 
              names:
                - default 
        relabel_configs: # filtering only the az-classifier service and port 8000
          - source_labels: [__meta_kubernetes_service_name]  
            regex: az-classifier 
            action: keep 
          - source_labels: [__meta_kubernetes_pod_container_port_number] 
            regex: "8000"
            action: keep